[package]
name = "geometry-rays-fyre"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
gr-rodio = "1.1.1"
ureq = "3.1.2"
mlua = { version = "0.11.4", features = ["lua54", "vendored"] }
futures = "0.3.31"
image = "0.25.8"
crossbeam = "0.8.4"
